### ISSUE TITLE
ユーザーは「タスク」を入力することができる

### ISSUE THREAD

**Issue by asash3** [IshizakiKeisuke/To-do-App#3]
# ストーリー
ユーザとして、
タスクを追加したい。
なぜなら、タスクは変化していくものだからだ。

# 機能仕様
* Enter or 「追加」ボタンを押した際、タスクがタスク一覧表末尾に追加される
* 500文字以内のタスクが入力・追加できる(byte単位ではない)
* ０文字での追加はできない
* 追加できなかった際は何も起きない

# やること
- [x] #10 
- [x] #11

**Comment by IshizakiKeisuke** [comment]
お疲れ様です。

タスク入力・追加の機能に関してなのですが、以下のことに関しまして、何か制約がありますでしょうか？

1. 何も記載、空白も開けていないタスクの追加について
2. 文字の制限(文字数・文字の種類と特殊文字)について

返信よろしくお願い致します。

**Comment by asash3** [comment]
> 1. 何も記載、空白も開けていないタスクの追加について

何も入力が無い状態でのタスク追加はNGとしてください。改行もNGです。

> 2.文字の制限(文字数・文字の種類と特殊文字)について

文字数は最大500文字としてください。
改行以外は何でも入力出来てOKです。

**Comment by IshizakiKeisuke** [comment]
承知しました。

追加できない際の警告文に関してなのですが、出力することは必要ですか？
必要だった場合、どのような出力がよろしかったでしょうか？

**Comment by asash3** [comment]
> 追加できない際の警告文に関してなのですが、出力することは必要ですか？

特に不要です。

**Comment by asash3** [comment]
@IshizakiKeisuke 
決定した内容については機能仕様に記載お願いします。
